export const UserActionTypes = {
  SET_NFT: "SET_NFT",
  SET_ACCOUNT: "SET_ACCOUNT",
  SET_BASE_COTRACT: "SET_BASE_COTRACT",
  SET_TRANSACTION_CONTRACT: "SET_TRANSACTION_CONTRACT"
};

export const ItemActionTypes = {
  SELECTED_NFT: "SELECTED_NFT",
  REMOVE_SELECTED_NFT: "REMOVE_SELECTED_NFT",
};
